### PR TITLE
Use array instead of `yield return`.

### LINKED ISSUE #106: Sequence.CreateSingle optimization
Profiling shows that array is much faster than `yield return`.

```cs
using System.Collections.Generic;
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;

namespace NS
{
    public class X
    {
        public IEnumerable<int> E() { yield return 1; }

        [Benchmark]
        public int EE()
        {
            int r = 0;
            foreach (var a in E()) r += a;
            return r;
        }

        public IEnumerable<int> A() { return new[] {1}; }

        [Benchmark]
        public int AA()
        {
            int r=0;
            foreach (var a in A()) r += a;
            return r;
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var summary = BenchmarkRunner.Run(typeof(Program).Assembly);
        }
    }
}
```

.NET Core
```
BenchmarkDotNet=v0.12.0, OS=Windows 10.0.18363
Intel Core i7-8565U CPU 1.80GHz (Whiskey Lake), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=3.1.200
  [Host]     : .NET Core 3.1.2 (CoreCLR 4.700.20.6602, CoreFX 4.700.20.6702), X64 RyuJIT
  DefaultJob : .NET Core 3.1.2 (CoreCLR 4.700.20.6602, CoreFX 4.700.20.6702), X64 RyuJIT

| Method |     Mean |    Error |   StdDev |
|------- |---------:|---------:|---------:|
|     EE | 26.12 ns | 0.539 ns | 0.854 ns |
|     AA | 19.31 ns | 0.415 ns | 0.478 ns |
```

.NET Framework
```
BenchmarkDotNet=v0.12.0, OS=Windows 10.0.18363
Intel Core i7-8565U CPU 1.80GHz (Whiskey Lake), 1 CPU, 8 logical and 4 physical cores
  [Host]     : .NET Framework 4.8 (4.8.4150.0), X64 RyuJIT
  DefaultJob : .NET Framework 4.8 (4.8.4150.0), X64 RyuJIT


| Method |     Mean |    Error |   StdDev |
|------- |---------:|---------:|---------:|
|     EE | 19.30 ns | 0.165 ns | 0.146 ns |
|     AA | 21.50 ns | 0.406 ns | 0.317 ns |
```

**Is your feature request related to a problem? Please describe.**
Replace implementation with array with single element.

### PR DESCRIPTION
**Pull request by NN---**
Fix #106

### CODE REVIEW

**Comment by andrewvk** [comment]
It is worth using conditional compilation and leaving the old code for .net fw.

**Comment by ig-sinicyn** [comment]
I'd check memory allocations for both versions. If there's no large impact, I'd prefer to keep a single solution (the one with array).

**Comment by NN---** [comment]
Given the amount of [generated](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA+ABADAAgwRhQG4BYAKAwGY8AmHAYRwG9yc329qDKAeASwB2AFwB8OAKIAKAJTM8+fHgDsOfERwBfcqw7sqOQUIlTpO3czPn2hnFBwBeHFlJkrugGbQYAQzAALHEkAN287bwMBCRlZOwBqR28XNw4MFSgkqy0yDSA===) code I don't know whether array is less memory efficient.

**Comment by ig-sinicyn** [comment]
We can check impact with help of the BDN's [MemoryDiagnoser](https://benchmarkdotnet.org/articles/configs/diagnosers.html) :)

**Comment by ig-sinicyn** [comment]
As far as I can see from the code, amount of allocations should be nearly identical for both versions.

**Pull request merged**
