### PR TITLE
Add code annotations.

### PR DESCRIPTION
**Pull request by NN---**
Add relevant NotNull, ItemNotNull annotations.

### CODE REVIEW

**Comment by ig-sinicyn** [comment]
LGTM

@andrewvk can you review the PR?

**Comment by ig-sinicyn** [comment]
LGTM again:)
@NN--- please add "[WIP]" to the title if the PR is not done yet. I've added https://github.com/apps/wip for that

**Comment by NN---** [comment]
@ig-sinicyn I would like to add more annotations, but first I need this PR to be accepted.

**Comment by ig-sinicyn** [comment]
@NN--- 

Sorry for the delay and thanks for the work. It's really cool!

**Pull request merged**
