### PR TITLE
Use Theraot.Core library

### PR DESCRIPTION
**Pull request by NN---**
This makes easier to support older frameworks:
* .NET 2.0, ..NET 3.0 - now have all features support except XLinq.
* .NET Standard 1.6, 1.5 - Almost everything is supported
* .NET Core 1.1, 1.0 - Almost everything is supported

### CODE REVIEW

**Comment by NN---** [comment]
Blocked by https://github.com/theraot/Theraot/issues/36

**Comment by ig-sinicyn** [comment]
1. 👍 

2. Can we keep current approach with `#if LESSTHAN_XXX` checks?
I'm afraid strict equality checks (`#if net35`) will be wary fragile and we'll have to update them for each new target.

**Comment by NN---** [comment]
Sure.
After Theraot library update fix, I'll revisit these conditions.

**Comment by NN---** [comment]
> Can we keep current approach with #if LESSTHAN_XXX checks?
My intention is to not bring additional dependency in newer .NET frameworks.
Therefore, I am afraid that for some cases there will be need for strict version check.

**Pull request merged**
