### PR TITLE
Improvements.

### PR DESCRIPTION
**Pull request by NN---**
Separate classes.
Add tests..

### CODE REVIEW

**Comment by andrewvk** [comment]
Maybe static method instead of type constructor is better, especially for HGlobal<T>?
Also, HGlobalScope logic can be implemented using CodeJam.Disposable.Create()

**Comment by NN---** [comment]
Ok.

**Comment by NN---** [comment]
Is it okay? Can you merge?

**Comment by andrewvk** [comment]
I can't see any commits other than initial.

**Pull request closed without merging**
